encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.index2, name="dis"),
    path("wiki/", views.rand, name="rand"),
    path("search/", views.search, name="search"),
    path("search/<str:title>", views.err, name="searcherr"),
    path("CNP/", views.CNP, name="CNP"),
    path("CNP/<str:title>", views.err, name="CNPerr"),
    path("edit/<str:title>", views.editEntry, name="edit"),
    path("<str:title>", views.err, name="error")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from . import util
from re import search
import markdown2 as markdown
from django import forms
import random

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def index2(request, title="error"):
    if(util.get_entry(title)):
        f = util.get_entry(title)
        return HttpResponse(render(request, "encyclopedia/displaywiki.html", {
            "title": title,
            "data":markdown.markdown(f)
        }))
    else:
        return render(request,"encyclopedia/error.html")


def search(request):
    if request.method == "POST":
        if util.get_entry(request.POST['q']):
            return HttpResponseRedirect("/wiki/"+request.POST['q'])
        else:
            list2 = []
            for i in util.list_entries():
                if request.POST['q'].lower() in i.lower():
                    list2.append(i)
            print(list2)
            if len(list2) == 0:
                return render(request,"encyclopedia/search.html",{
                    "false":True,
                    "entries":list2
            })
            else:
                return render(request,"encyclopedia/search.html",{
                    "false":False,
                    "entries":list2
            })


def CNP(request):
    if request.method == "POST":
        print(request.POST)
        flag = 0
        for i in util.list_entries():
            if request.POST['title'].lower().strip() == i.lower():
                flag = 1
                return render(request, "encyclopedia/EntryPage.html",{
                "newpage":True,
                "error":True,
                "title":request.POST['title'],
                "value":request.POST['text']
                })
        if flag == 0:
            util.save_entry(request.POST['title'],request.POST['text'])
        return HttpResponseRedirect("/")
    return render(request, "encyclopedia/EntryPage.html",{
        "newpage":True,
        "title":"",
        "value":""
    })


def editEntry(request, title):
    if request.method == "POST":
        print(request.POST)
        print(request.POST['title'])
        util.save_entry(request.POST['title'],request.POST['text']) 
        print(f"name of new file created {request.POST['title']}.md")
        return HttpResponseRedirect("/")    
    f = util.get_entry(title)  
    return render(request,"encyclopedia/EntryPage.html",{
        "newpage":False,
        "title":title,
        "value":f
    })

def rand(request):
    print(random.choice(util.list_entries()))
    return HttpResponseRedirect("/wiki/"+random.choice(util.list_entries()))


def err(request, title):
    return render(request,"encyclopedia/error.html")

encyclopedia/templates/encyclopedia/EntryPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  {% if newpage %}
        New page
   {% else %}     
       {{ title }}
    {% endif %}   
{% endblock%}

{% block body %}
    {% if newpage %}
      <h1> New page</h1>
      <form action="{% url 'encyclopedia:CNP' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="title" placeholder="Title" value="{{ title }}">
      {% if error %}
       <h3> An entry already exist with this title</h3>
      {% endif %}
    {% else %}     
      <h1> {{ title }} </h1>
      <form action="/edit/{{ title }}" method="POST">
      {% csrf_token %}
      <input type="text" name="title" placeholder="Title" value="{{ title }}" hidden>
    {% endif %} 
      <br>
      <label for="text"> enter the Markdown content below:</label>
      <textarea name="text" placeholder="Start with the title of the page . . .">{{ value }}</textarea>      
      <input type="submit" value="Save">
      </form>
{% endblock%}

encyclopedia/templates/encyclopedia/displaywiki.html
{%  extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
  {{ data|safe }}
  <br>
  <a href="/edit/{{ title }}">Click here to edit this page ></a>
{% endblock%}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Page Not Found</h1>
    <br>
    <h3> Looks like the page you are looking for does not exist.</h3>
    <br>
    <h3><a href="/">click here to return to home page ></a></h3>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{entry}}" > {{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search'%}" method="POST">
                    {% csrf_token%}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                     <a href="{% url 'encyclopedia:CNP' %}">Create New Page</a>
                </div>
                <div>
                    <a href="/wiki/"> Random Page </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
   Search
{% endblock %}

{% block body %}
   <h1> Search Results</h1>
       {% if false %}
           <h3> Could not found any related pages to your search...</h3>
        {% else %}   
        <ul>
            {% for entry in entries %}
                <li><a href="/wiki/{{entry}}">{{entry}}</a></li>
            {% endfor %}
        </ul> 
        {% endif %}    
{% endblock %}